import{a as b,s as f,i as d}from"./assets/vendor-7eea9cc0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const v="https://pixabay.com/api/";async function m(i,e=1,n){try{return(await b.get(v,{params:{key:"44959261-ea439a2adbf8f7e5770dfe1a3",image_type:"photo",orientation:"horizontal",safesearch:!0,q:i,page:e,per_page:15}})).data}catch(s){console.error("Fetch error: ",s)}}const p=document.querySelector(".gallery");function M({webformatURL:i,largeImageURL:e,tags:n,likes:s,views:t,comments:o,downloads:a}){return`<li class="gallery-item> 
    <figure class="sign">
        <a href="${e}"><img class="list-img" src="${i}" alt="${n}" title="" width="360" height="200"/></a><span class="title-img">
        <figcaption class="title-img"><ul class="figcaption">
      <li class="figcaption-item">Likes<p class="counter">${s}</p></li>
      <li class="figcaption-item">Views<p class="counter">${t}</p></li>
      <li class="figcaption-item">Comments<p class="counter">${o}</p></li>
      <li class="figcaption-item">Downloads<p class="counter">${a}</p></li>
    </ul></figcaption>
    </figure>
   </li>`}function g(i){return i.map(M).join("")}function w(i){const e=g(i);p.innerHTML=e}function E(i){const e=g(i);p.insertAdjacentHTML("beforeend",e)}const r={btnSubEl:document.querySelector(".btn-search"),formEl:document.querySelector(".form"),input:document.querySelector('[name="text"]'),ul:document.querySelector("ul"),btnLoadMore:document.querySelector(".load-more")};let h=0,c,l=1;r.formEl.addEventListener("submit",async i=>{try{if(i.preventDefault(),y(),c=r.input.value.trim(),l=1,!c)q();else{const e=await m(c,l);h=Math.ceil(e.totalHits/15),e.hits.length===0&&S(),w(e.hits),L(75);const n=new f(".gallery a");r.btnLoadMore.classList.remove("visually-hidden"),r.formEl.addEventListener("click",s=>{s.target.name==="text"&&(r.input.value="")})}}catch(e){console.log(e.message)}u()});r.btnLoadMore.addEventListener("click",async()=>{if(r.btnLoadMore.classList.add("visually-hidden"),y(),l===h)return r.btnLoadMore.classList.add("visually-hidden"),u(),x();l+=1;const i=await m(c,l);E(i.hits),new f(".gallery a").refresh(),u(),L(),r.btnLoadMore.classList.remove("visually-hidden")});function q(){return console.log("sdsd"),r.ul.innerHTML="",r.btnLoadMore.classList.add("visually-hidden"),d.error({message:"Please fill in the input field",position:"topRight"})}function S(){d.error({message:"Image is not found",position:"topRight"})}function x(){d.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"})}function y(){r.btnLoadMore.insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>')}function u(){document.querySelector(".loader").remove()}function L(i){const e=r.ul.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:i||e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
