import{a as p,i as u,S as g}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const d=document.querySelector(".gallery");function h({webformatURL:o,largeImageURL:t,tags:s,likes:l,views:e,comments:r,downloads:i}){return`<li class="gallery-item> 
    <figure class="sign">
        <a href="${t}"><img class="list-img" src="${o}" alt="${s}" title="" width="360" height="200"/></a><span class="title-img">
        <figcaption class="title-img"><ul class="figcaption">
      <li class="figcaption-item">Likes<p class="counter">${l}</p></li>
      <li class="figcaption-item">Views<p class="counter">${e}</p></li>
      <li class="figcaption-item">Comments<p class="counter">${r}</p></li>
      <li class="figcaption-item">Downloads<p class="counter">${i}</p></li>
    </ul></figcaption>
    </figure>
   </li>`}function f(o){return o.map(h).join("")}function y(o){const t=f(o);d.innerHTML=t}function L(o){const t=f(o);d.insertAdjacentHTML("beforeend",t)}function b(){document.querySelector(".gallery").insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>')}function v(){document.querySelector(".loader").remove()}function m(o,t){b();const s="https://pixabay.com/api/",l={params:{key:"44959261-ea439a2adbf8f7e5770dfe1a3",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}};p.get(s,l).then(e=>{if(!e)throw new Error(e.status);return e.data}).then(e=>{if(e.total!==0){if(t>1)L(e.hits);else{const i=Math.ceil(e.totalHits/15);console.log(i),t<i?y(e.hits):(document.querySelector(".load-more").classList.add("visually-hidden"),u.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}new g(".gallery a").refresh()}else u.error({message:"Image is not found",position:"topRight"})}).catch(e=>console.log(e)).finally(()=>{v()})}const n={btnSubEl:document.querySelector(".btn-search"),formEl:document.querySelector(".form"),input:document.querySelector('[name="text"]'),ul:document.querySelector("ul"),btnLoadMore:document.querySelector(".load-more")};let c,a=1;n.formEl.addEventListener("submit",o=>{o.preventDefault(),c=n.input.value.trim(),a=1,c?(m(c,a),document.querySelector(".load-more").classList.remove("visually-hidden"),n.formEl.addEventListener("click",t=>{t.target.name==="text"&&(n.input.value="")})):u.error({message:"Please fill in the input field",position:"topRight"})});n.btnLoadMore.addEventListener("click",()=>{a+=1,console.log(a),m(c,a)});
//# sourceMappingURL=commonHelpers.js.map
